# override this to use external elasticsearch
elasticsearch:
  enabled: true
  host: "pelias-elasticsearch-service"
  port: 9200
  protocol: "http"
  pvc:
   create: true
   name: elasticsearch-pvc
   storageClass: efs-storageclass
   accessModes: ReadWriteMany
   storage: 40Gi

canary:
  elasticsearch:
    host: null

## API settings
api:
  replicas: 1
  canaryReplicas: 0
  dockerTag: "latest"
  canaryDockerTag: null # set this value to enable the canary deployment
  indexName: "pelias"
  serviceType: "NodePort"
  accessLog: "common" # allows configuring access log format. Empty string disables access log
  autocomplete:
    exclude_address_length: 0
  targets:
    auto_discover: null # use default value
  exposeInternalDebugTools: false
  requests:
    memory: 0.25Gi
    cpu: 0.1
  minReadySeconds: 10
  nodeSelector: {}
  ingress:
    enabled: true
    hostname: "pelias-api.litec-la.link"
    annotations:
      alb.ingress.kubernetes.io/group.name: "app-ingress"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/scheme: "internal"
      external-dns.alpha.kubernetes.io/hostname: "pelias-api.litec-la.link"
      kubernetes.io/ingress.class: "alb"

placeholder:
  enabled: true
  replicas: 1
  host: "http://pelias-placeholder-service:3000/"
  dockerTag: "latest"
  maxSurge: 1
  maxUnavailable: 0
  minReadySeconds: 5
  storeURL: "https://s3.amazonaws.com/pelias-data.nextzen.org/portland-metro/placeholder/store.sqlite3.gz"
  cpus: 1 # how many CPUs to allow using via the npm `cluster2` module
  retries: 1 # number of time the API will retry requests to placeholder
  timeout: 5000 # time in ms the API will wait for placeholder responses
  downloadCommand: >
    mkdir -p /data/placeholder/ &&
    wget -O- "$DOWNLOAD_URL" | gunzip > /data/placeholder/store.sqlite3
  limits:
    # cannot use a hyphen to match the k8s param due to https://github.com/helm/helm/issues/2192
    ephemeral_storage: 5Gi
  requests:
    memory: 512Mi
    cpu: 0.1
    # cannot use a hyphen to match the k8s param due to https://github.com/helm/helm/issues/2192
    ephemeral_storage: 5Gi
  annotations: {}
  nodeSelector: {}
  pvc: {}
#    create: true
#    name: placeholder-pvc
#    storageClass: aws-efs
#    accessModes: ReadWriteMany
#    storage: 10Gi
#    annotations: {}

libpostal:
  enabled: true
  replicas: 1
  host: "http://pelias-libpostal-service:4400/"
  dockerTag: "latest"
  maxSurge: 1
  maxUnavailable: 0
  minReadySeconds: 5
  retries: 1 # number of time the API will retry requests to libpostal
  timeout: 5000 # time in ms the API will wait for libpostal responses
  annotations: {}
  nodeSelector: {}

interpolation:
  enabled: true
  replicas: 1
  host: "http://pelias-interpolation-service:3000/"
  dockerTag: "latest"
  maxSurge: 1
  maxUnavailable: 0
  minReadySeconds: 5
  # URL prefix of location where streets.db and address.db will be downloaded
  downloadPath: "https://s3.amazonaws.com/pelias-data.nextzen.org/portland-metro/interpolation"
  retries: 1 # number of time the API will retry requests to interpolation service
  timeout: 5000 # time in ms the API will wait for interpolation service responses
  downloadCommand: >
    mkdir -p /data/interpolation/ &&
    wget -O - $DOWNLOAD_PATH/street.db.gz | gunzip > /data/interpolation/street.db &
    wget -O - $DOWNLOAD_PATH/address.db.gz | gunzip > /data/interpolation/address.db
  limits:
    # cannot use a hyphen to match the k8s param due to https://github.com/helm/helm/issues/2192
    ephemeral_storage: 5Gi
  requests:
    memory: 2Gi
    cpu: 0.1
    # cannot use a hyphen to match the k8s param due to https://github.com/helm/helm/issues/2192
    ephemeral_storage: 5Gi
  annotations: {}
  nodeSelector: {}
  pvc:
   create: true
   name: interpolation-pvc
   storageClass: efs-storageclass
   accessModes: ReadWriteMany
   storage: 10Gi
#    annotations: {}

pip:
  enabled: true
  replicas: 1
  host: "http://pelias-pip-service:3102/"
  dockerTag: "latest"
  maxSurge: 1
  minReadySeconds: 5
  maxUnavailable: 0 # adjusts rolling update settings
  retries: 1 # number of time the API will retry requests to the pip service
  timeout: 5000 # time in ms the API will wait for pip service responses
  initialDelaySeconds: 300 # pip service takes a long time to start up
  downloadCommand: "./bin/download --admin-only"
  limits:
    memory: 10Gi
    cpu: 3
    # cannot use a hyphen to match the k8s param due to https://github.com/helm/helm/issues/2192
    ephemeral_storage: 35Gi
  requests:
    memory: 5Gi
    cpu: 0.1
    # cannot use a hyphen to match the k8s param due to https://github.com/helm/helm/issues/2192
    ephemeral_storage: 35Gi
  annotations: {}
  nodeSelector: {}
  pvc:
   create: true
   name: pip-pvc
   storageClass: efs-storageclass
   accessModes: ReadWriteMany
   storage: 10Gi
#    annotations: {}

dashboard:
  enabled: true
  replicas: 1
  dockerTag: "latest"
  nodeSelector: {}
  serviceType: "NodePort"
  ingress:
    enabled: true
    hostname: "pelias-dashboard.litec-la.link"
    annotations:
      alb.ingress.kubernetes.io/group.name: "app-ingress"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/scheme: "internal"
      external-dns.alpha.kubernetes.io/hostname: "pelias-dashboard.litec-la.link"
      kubernetes.io/ingress.class: "alb"

healthlogger:
  replicas: 0
  dockerTag: "latest"
  maxSurge: 1
  maxUnavailable: 0
  minReadySeconds: 1
  requests:
    memory: 100Mi
    cpu: 0.1
  annotations: {}
  nodeSelector: {}
  watch_interval: 60

# Importer settings
# https://github.com/pelias/geonames
geonames:
  countryCode: "AU"
# https://github.com/pelias/openaddresses
openaddresses:
  files:
    - "au/countrywide.csv"
# https://github.com/pelias/openstreetmap
openstreetmap:
  download:
    - sourceURL: "http://download.geofabrik.de/australia-oceania/australia-latest.osm.pbf"
  import:
    - filename: "australia-latest.osm.pbf"
# https://github.com/pelias/whosonfirst
whosonfirst:
  countryCode: "AU"
  importPlace:
    - "85632793"

# For the 'build'
polylinesDownloadURL: "https://s3.amazonaws.com/pelias-data.nextzen.org/polylines/road_network.gz"
efs:
   storageClassName: "efs-storageclass"
